diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=main
core.editor="C:\Users\ecoliveira\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait
credential.http://siscanproxy.sispro.com.br:3128.provider=generic
http.https://domain.com.proxy=http://ecoliveira:nyerAM10@siscanproxy2.sispro.com.br:3128
https.https://domain.com.proxy=http://ecoliveira:nyerAM10@siscanproxy2.sispro.com.br:3128
http.sslverify=false
http.proxy=http://ecoliveira:icantsl55P@siscanproxy2.sispro.com.br:3128
https.proxy=http://ecoliveira:icantsl55P@siscanproxy2.sispro.com.br:3128
user.name=ERICK Carvalho Paulette de Oliveira
user.email=erickzcarvalho25@outlook.com
http.https://sispro.com.br=http://ecoliveira:icantsl55P@siscanproxy2.sispro.com.br:3128
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
